# Generated by Django 3.1.3 on 2021-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallTouchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_node', models.CharField(max_length=150)),
                ('ct_token', models.CharField(max_length=150)),
                ('ct_cabinet_id', models.IntegerField()),
                ('ct_user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
