# Generated by Django 3.1.3 on 2021-02-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallTouchModel',
        ),
    ]
