# Generated by Django 3.1.3 on 2021-02-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_calltouchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltouchmodel',
            name='ct_created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
