# Generated by Django 3.1.3 on 2021-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_calltouchmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltouchmodel',
            name='name',
            field=models.CharField(auto_created='CallTouch', default='CallTouch', max_length=50),
        ),
    ]
