# Generated by Django 3.1.3 on 2021-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20210202_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links_original_link', models.CharField(max_length=150)),
                ('links_upload_date', models.DateField(auto_now=True)),
                ('links_user_id', models.IntegerField(default=0)),
            ],
        ),

    ]
