# Generated by Django 3.1.3 on 2021-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_linkstocheck_linkstocheckresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('upload_date', models.DateField(auto_now=True)),
                ('original_link', models.CharField(max_length=150)),
                ('original_link_status_code', models.CharField(max_length=50)),
                ('redirect_link', models.CharField(max_length=150)),
                ('redirect_link_status_code', models.CharField(max_length=50)),
                ('history', models.CharField(max_length=150)),
                ('history_check_date', models.CharField(max_length=150)),
            ],
        ),
    ]
